---
title: "Spatial Var Data Viz"
author: Feride Karatas 
---

```{r}
# Load required libraries
library(tidyverse)
library(openintro)
library(ggplot2)

```

```{r}

# Import starbucks location data
starbucks <- read.csv("https://mac-stat.github.io/data/starbucks.csv")

# Keep only stores in contiguous US
starbucks_us <- starbucks |>
  filter(Country == "US", !State.Province %in% c("AK", "HI"))



starbucks_us_by_state <- starbucks_us |>
  count(Longitude, Latitude, State.Province) |>

  mutate(state_name = str_to_lower(abbr2state(State.Province)))



census_pop_est_2018 <- read_csv("https://mac-stat.github.io/data/us_census_2018_state_pop_est.csv") |>
  separate(state, into = c("dot", "state"), extra = "merge") |>
  select(-dot) |>
  mutate(state = str_to_lower(state))

starbucks_with_2018_pop_est <-
  starbucks_us_by_state |>
  left_join(census_pop_est_2018,
    by = c("state_name" = "state")
  ) |>
  mutate(starbucks_per_10000 = (n / est_pop_2018) * 10000)



library(leaflet)
library(gplots)
library(ggplot2)
library(maps)

head(starbucks_with_2018_pop_est)


state_map <- map_data("state")  # Gets US state map data
head(state_map)

# Map visualization
ggplot(data = starbucks_with_2018_pop_est, aes(map_id = state_name, fill = starbucks_per_10000)) +
  geom_map(map = state_map) +
  expand_limits(x = state_map$Long, y = state_map$Lat) +
  geom_point(data = starbucks_with_2018_pop_est, aes(x = Longitude, y = Latitude), color = 'darkgreen', alpha = 0.5, size = 0.5) +
  labs(title = "Starbucks per 10,000 People in the Contiguous U.S.",
       fill = "Starbucks per 10,000",
       caption = "Plot created by Feride") +
  theme_minimal() +
  scale_fill_gradientn(name = "Starbucks per 10k", colors = c("blue", "green", "pink", "red")) +
  theme(legend.position = "bottom")

```
