---
title: "soloproject"
format: html
---



```{r}
library(sf)
library(tidyverse)
library(ggplot2)
library(mosaic)
testscore <- read.csv("https://vincentarelbundock.github.io/Rdatasets/csv/AER/CASchools.csv")
cal_boundries <- read_sf("../data/California_County_Boundaries_8408091426384550881/cnty19_1.shp")

ggplot(cal_boundries)+
  geom_sf()
```

```{r}

# Prepare test score data by averaging income per county
testscore_summary <- testscore %>%
  group_by(county) |>
  summarize(income = mean(income, na.rm = TRUE))

# Join with shapefile data
cal_boundries <- cal_boundries %>%
  left_join(testscore_summary, by = c("COUNTY_NAM" = "county"))

# Plot Choropleth
ggplot(cal_boundries) +
  geom_sf(aes(fill = income)) +
  scale_fill_viridis_c(option = "plasma") +  # Better visualization
  theme_minimal() +
  labs(title = "Choropleth of Income by County",
       fill = "Average Income")+
  theme_map()


 

```

```{r}

testscore_summary <- testscore %>%
  group_by(county) |>
  summarize(math = mean(math, na.rm = TRUE))

# Join with shapefile data
cal_boundries <- cal_boundries %>%
  left_join(testscore_summary, by = c("COUNTY_NAM" = "county"))

# Plot Choropleth
ggplot(cal_boundries) +
  geom_sf(aes(fill = math)) +
  scale_fill_viridis_c(option = "plasma") +  # Better visualization
  theme_minimal() +
  labs(title = "Choropleth of Math Score by County",
       fill = "Average Math Score")+
  theme_map()

```

```{r}

testscore_summary <- testscore %>%
  group_by(county) |>
  summarize(students = mean(students, na.rm = TRUE))

# Join with shapefile data
cal_boundries <- cal_boundries %>%
  left_join(testscore_summary, by = c("COUNTY_NAM" = "county"))

# Plot Choropleth
ggplot(cal_boundries) +
  geom_sf(aes(fill = math)) +
  scale_fill_viridis_c(option = "plasma") +  # Better visualization
  theme_minimal() +
  labs(title = "Choropleth of Math Score by County",
       fill = "Average Math Score")+
  theme_map()
```

