---
title: "Univariate Viz"
---

Use this file for practice with the **univariate viz** in-class activity.  Refer to the class website for details.

# Import data
```{r}
library(ggplot2)
library(tidyverse)

hikes <- read.csv("https://mac-stat.github.io/data/high_peaks.csv")
view(hikes)
```

```{r}

head(hikes)
# Use the ggplot function
ggplot(hikes, aes(x = rating,)) + 
  geom_bar(color= "orange", fill = ("purple")) +
  labs( x= "Rating", y= "Number of Hikes") +
  theme_minimal()
```
```{r}
# COMMENT on the change in the code and the corresponding change in the plot
ggplot(hikes, aes(x = elevation)) +
  geom_histogram(color= "white", binwidth = 100) +
  labs(x = "Elevation (feet)", y = "Number of hikes")

```

```{r}
ggplot(hikes,aes(x= elevation)) +
  geom_density(color= "orange", fill= "pink")

```

```{r}
# YUCK 
ggplot(hikes, aes(x = elevation)) + geom_histogram(color = "white", binwidth = 200) + labs(x = "Elevation (feet)", y = "Number of hikes")
```
```{r}
# Data on students in this class
survey <- read.csv("https://hash-mac.github.io/stat112site-s25/data/survey.csv")
view(survey)
```

```{r}
library(tidyverse)

  ggplot( survey, aes(x= cafe_mac)) +
            geom_bar(color= "pink") +
     theme_minimal()
 
```

