---
title: "Strings"
format: html
---

```{r}
library(tidyverse)

classes <- data.frame(
  sem        = c("SP2023", "FA2023", "SP2024"),
  area       = c("History", "Math", "Anthro"),
  enroll     = c("30 - people", "20 - people", "25 - people"),
  instructor = c("Ernesto Capello", "Lori Ziegelmeier", "Arjun Guneratne")
)

classes
```

```{r}
# Define a new variable "num" that adds up the number of characters in the area label
mutate(classes, num= str_length(area))
```

```{r}
# Change the areas to "history", "math", "anthro" instead of "History", "Math", "Anthro"
mutate(classes, area= str_to_lower(area))
```

```{r}
# Create a variable that id's which courses were taught in spring
mutate(classes, id= str_detect(sem, "SP"))
```

```{r}
# Change the semester labels to "fall2023", "spring2024", "spring2023"
mutate(classes, semlabels= str_replace(sem, "SP", "spring")) |>
  mutate(classes, semlabels= str_replace(sem, "FA", "fall"))
  
```

```{r}
# In the enroll variable, change all e's to 3's (just because?)
mutate(classes, enroll= str_replace(enroll,"e", "3s" ))
```

```{r}
# Use sem to create 2 new variables, one with only the semester (SP/FA) and 1 with the year
mutate(classes, semester= str_sub(sem,1,2),
year= str_sub(sem,3,6))
```
```{r}
# How can we do this after mutating?
classes |> 
  mutate(spring = str_detect(sem, "SP"))
```

```{r}
# We don't have to mutate first!
classes |> 
  filter(str_detect(sem, "SP"))
```

```{r}
classes|>
  # Yet another way
  filter(!str_detect(sem, "FA"))
```

```{r}
#Suppose we wanted to get separate columns for the first and last names of each course instructor in classes. Try doing this using str_sub(). But don’t try too long! Explain what trouble you ran into.

classes|> 
  mutate( instructor= str_sub(sem,1,2))
```

